### ISSUE TITLE
https://rivestream.netlify.app/ is the only domain working.

### ISSUE THREAD

**Issue by vantage-ola** [Developabile/rive-next#114]
beatiful service... this is nice, but the netlify deploy is the only one currently working or i can assess

**Comment by dev-AshishRanjan** [comment]
@vantage-ola ,
Thanks for letting me know.
I have updated the `.live` domain
`vercel` has stopped
`netlify` is working

https://github.com/Developabile/rive-next/blob/dev/Domains.md

**Comment by vantage-ola** [comment]
@dev-AshishRanjan alright. good stuff
