### ISSUE TITLE
Website is too slow 

### ISSUE THREAD

**Issue by neutralxd** [Developabile/rive-next#117]
I recently deployed this repo on localhost as well as VPS server also, but it feels too slow, it takes almost 5-8s to open website or navigate to another page, any way to speed up I am new to react and next js

**Comment by dev-AshishRanjan** [comment]
use page cache systems of cloudflare
It will cache the pages of the website

**Comment by neutralxd** [comment]
> use page cache systems of cloudflare It will cache the pages of the website

problem is not consecutive, sometimes it takes more then 10s to load page
also facing firebase problem on signing up on site
![Screenshot (308)](https://github.com/Developabile/rive-next/assets/133840661/345256cf-39d7-4596-92a6-045154ec79bd)

**Comment by dev-AshishRanjan** [comment]
@neutralxd ,  
You have to allow the domains which would use firebase  
In the firebase console add those domains

**Comment by neutralxd** [comment]
> @neutralxd , You have to allow the domains which would use firebase In the firebase console add those domains

Sorry my bad Actually I deployed in dev instead of build now everything working well

**Comment by neutralxd** [comment]
> @neutralxd , You have to allow the domains which would use firebase In the firebase console add those domains

hello what will be the externalprovider url and provider url

**Comment by dev-AshishRanjan** [comment]
ExternalProvider url has been decrypted 

We use external provider only

External provider is a scrapper to scrape media links from vidsrc.pro

We are not going public with the link due to high traffic
