### ISSUE TITLE
The MacOS App Is Damaged

### ISSUE THREAD

**Issue by The-UnknownHacker** [Developabile/rive-next#119]
Whenever I try to open the app on macos I get the following error

“Rive” is damaged and can’t be opened. You should move it to the Bin.

This is on Apple Silicon M2

**Comment by dev-AshishRanjan** [comment]
@The-UnknownHacker ,
can you share the screenshot

we are using tauri app to create desktop apps

**Comment by The-UnknownHacker** [comment]
<img width="455" alt="Screenshot 2024-07-11 at 7 07 36 pm" src="https://github.com/Developabile/rive-next/assets/128781393/9aca5474-e32c-4127-94f9-01e2f24b035b">

**Comment by dev-AshishRanjan** [comment]
> <img alt="Screenshot 2024-07-11 at 7 07 36 pm" width="455" src="https://private-user-images.githubusercontent.com/128781393/347755003-9aca5474-e32c-4127-94f9-01e2f24b035b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2OTI0ODksIm5iZiI6MTcyMDY5MjE4OSwicGF0aCI6Ii8xMjg3ODEzOTMvMzQ3NzU1MDAzLTlhY2E1NDc0LWUzMmMtNDEyNy05NGY5LTAxZTJmMjRiMDM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMDAzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmU2ZTMwNjE0ZDUwM2Y3YjBmZTdjZTFmYzc3YzYyNDNkYjg4YmQ4MjViZWFkM2U3OGFiNmQxNWQwN2RhYjFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o3xGE-uXeYKs7BcEdvsCN_Hu0QP3-knDw8Al4ZXkA5c">

You have to bypass the security of macos. we have to give permission on windows also  
You have to follow the same process which is followed during installation of electron apps like vscode

**Comment by The-UnknownHacker** [comment]
Where can I bypass this

**Comment by dev-AshishRanjan** [comment]
For now use PWA,

Go to settings>downloads
Refresh the downloads page and click on download button
Then click install on the popup

You have to install PWA using your preferred browser

**Comment by The-UnknownHacker** [comment]
the best solution I found in this case was this

# Removing Extended Attributes (xattrs) from a macOS Application

In some situations, extended attributes (xattrs) may cause issues with applications on macOS. This guide demonstrates how to use the `xattr` command to remove these xattrs.

## Example Usage

1. Open Terminal.app or any other terminal emulator on your Mac.

2. Navigate to the appropriate directory where your application is located using the `cd` command. For example:

    ```bash
    cd /Applications
    ```

3. Run the following command to remove all extended attributes from the "Rive" application:

    ```bash
    xattr -cr Rive.app
    ```

    Replace `Rive.app` with the name of your desired application if needed.

    This command will recursively (`-r`) remove all user-defined extended attributes (`-cr`) from the specified application file.

4. After running this command, you should no longer encounter issues related to extended attributes within the targeted application.
