### ISSUE TITLE
questions regarding the env details

### ISSUE THREAD

**Issue by skgupta507** [Developabile/rive-next#30]
hello @dev-AshishRanjan can i take few minutes of yours.
i have a doubt in what to add in the .env file can u please explain it to me.
your help will be apprieciatred.  by the way i really liked ur website the design and workability of it

**Comment by dev-AshishRanjan** [comment]
# How to create the .env file

The .env file will be created based on .env.example
The values to be filled are:
## 1. Firebase configuration 
  ``` .env
  NEXT_PUBLIC_FB_API_KEY=
NEXT_PUBLIC_FB_AUTH_DOMAIN=
NEXT_PUBLIC_FB_PROJECT_ID=
NEXT_PUBLIC_FB_STORAGE_BUCKET=
NEXT_PUBLIC_FB_SENDER_ID=
NEXT_PUBLIC_FB_APP_ID=
NEXT_PUBLIC_FB_MEASUREMENT_ID=
  ```
  Steps to get the credentials:
 - Go to the [Firebase Console](https://console.firebase.google.com/).
- Create a new project or select an existing one.
- Navigate to Project Settings > General.
- Under Your apps, click on the Web app (</>) icon to register a new app.
- Copy the config object's values into your `.env` file.

## 2. TMDB configuration

``` .env
  NEXT_PUBLIC_TMDB_API=https://api.themoviedb.org/3
  NEXT_PUBLIC_TMDB_API_KEY=
  NEXT_PUBLIC_TMBD_IMAGE_URL=https://image.tmdb.org/t/p/original/
```
Steps to get TMDB API KEY
- Go to the [TMDB website](https://www.themoviedb.org/).
- Sign up or log in to your account.
- Navigate to Account Settings > API.
- Request an API key if you don't have one already.
- Copy your API key into your `.env` file.

## 3. Video Streaming API
``` .env
NEXT_PUBLIC_STREAM_URL_AGG=
NEXT_PUBLIC_STREAM_URL_VID=
NEXT_PUBLIC_STREAM_URL_PRO=
NEXT_PUBLIC_STREAM_URL_EMB=
NEXT_PUBLIC_STREAM_URL_MULTI=
NEXT_PUBLIC_STREAM_URL_SUP=
```

These are all the different streaming services used, that can't be disclosed directly.
But I can give you a hint..

> [!TIP]
> We offer free streaming links for movies and episodes that can be
> effortlessly integrated into your website through our embed links, API

You can do some research over internet using this quote to get the services.

If there are anymore env vars left, give them any random values, as they were used in dev only and not in prod.

Happy Coding :)

**Comment by dev-AshishRanjan** [comment]
@skgupta507 ,

You don't have to integrate them as API
use the embed system i.e `iframe` and the src would be as instructed by the services.
On the website of these services, they have provided enough documentation on how to use the embed system.

And if you are going to create your own website, then I would recommend to go through [github-issue](https://github.com/AdvithGopinath/LetMeWatch/issues/4).
If you do some researching, then you will find the right services here.

And as for the source for all the service provider used here, there no source, I just stumbled across them from time to time.
But it's better to use our website (which is already created), than going through the hassle of creating your own. But if it's for education purpose then go for it.

**Comment by skgupta507** [comment]
Thanks for ur support @dev-AshishRanjan  I was able to find some good sources n use then ur help was really appreciated😊. 
Plus the design the structure of the site u made is really awesome👍👏. Really loved it bro.
