### ISSUE TITLE
[💡 Idea] File type labels

### ISSUE THREAD

**Issue by BjornLV** [Developabile/rive-next#49]
Maybe add a label like HD, SD, CAM too the movie posters. Probably can we requested with the API.

**Comment by dev-AshishRanjan** [comment]
@BjornLV ,
I had thought about this but as of now there is no API to know the video quality from the video provider before hand.
And all the video provider have multiple video quality support.

But if they release any then I will for sure integrate them.
Any PR are also welcomed.
