### ISSUE TITLE
Scrolling dragging

### ISSUE THREAD

**Issue by BjornLV** [Developabile/rive-next#59]
Scrolling dragging through style_HomeListSection__BKDhh or any other List Sections does not work on PC. (This does work on mobile)
![image](https://github.com/Developabile/rive-next/assets/79105721/14ffec61-db0e-4cb4-9724-1e150acebc2a)

**Comment by dev-AshishRanjan** [comment]
@BjornLV ,

This is made such that we can scroll using touchpad for laptops
We removed scrollbars because it is not professional

**Comment by BjornLV** [comment]
![idea](https://github.com/Developabile/rive-next/assets/79105721/7e2901b3-ccc4-4008-97b2-96c5ceacd9f1)

You could always add something like this so desktop scrolling is also supported. Right now there is no real solution to scroll thought those lists on desktops, which is a shame.

**Comment by dev-AshishRanjan** [comment]
@BjornLV ,

On your suggestion, scroll feature has been implemented

**Comment by dev-AshishRanjan** [comment]
Closing this issue as completed
