### ISSUE TITLE
I figured out where you used apis from but still need some help

### ISSUE THREAD

**Issue by chitrakshbotwala** [Developabile/rive-next#70]
SO is it neccassary i use apis from rapid or i can use any other api that provides these functionalities also it would be nice if you could lemme know what you used you could mail me at chitraksh2705@gmail.com or dm me on discord - yupcm ( my username )

**Comment by dev-AshishRanjan** [comment]
I have mailed you all the required environment variables

**Comment by chitrakshbotwala** [comment]
Thankyou so much

**Comment by chitrakshbotwala** [comment]
> I have mailed you all the required environment variables

Checked my mail didn't receive anything , also by required vars you mean the apis where you got the data from right? Cause I've already checked the env example and about env I just don't know what APIs to use @dev-AshishRanjan

**Comment by chitrakshbotwala** [comment]
also I checked rapid they dont have any relevant apis so if you could mail me what api's you used that would help a lot

**Comment by dev-AshishRanjan** [comment]
If you got the env, then you can close this issue

**Comment by chitrakshbotwala** [comment]
yup got the env , ill be closing this now thanks for the help, cheers !
