### ISSUE TITLE
It's a request on settings 

### ISSUE THREAD

**Issue by Drac1652** [Developabile/rive-next#79]
Am a anime fan and not much of a fan on movies, tv shows and especially a K dramas.
Is there any way you can add settings to choose what to display on homepage so if i only want anime then only anime can be displayed or if i want anime and movies only the two can be displayed.

**Comment by dev-AshishRanjan** [comment]
This can be done
But homepage is always about, what different services your product can offer
And as Movies, Tv shows, Anime and K-drama are available, we are showing all these

For animes you can go to [Anime-section](https://rivestream.vercel.app/anime)
It's the anime section of the Rive.
You will get various animes here (data available as per TMDB)
