### ISSUE TITLE
vidsrc scraper

### ISSUE THREAD

**Issue by gfxnick** [Developabile/rive-next#90]
when i use the vidsrc scraper and use the endpoints i get the arrays not the streams can you tell me how you guys got the streaming im embediding the endpoints and still the same

**Comment by dev-AshishRanjan** [comment]
We are using self-made scrapper
for movie: `https://rive-vidsrc-scrapper.vercel.app/movie/278`
for tv shows : `https://rive-vidsrc-scrapper.vercel.app/tv/1396/1/1`

the github repo of the scrapper is private, and above are the endpoints

**Comment by gfxnick** [comment]
> We are using self-made scrapper for movie: `https://rive-vidsrc-scrapper.vercel.app/movie/278` for tv shows : `https://rive-vidsrc-scrapper.vercel.app/tv/1396/1/1`
> 
> the github repo of the scrapper is private, and above are the endpoints

also the service you scrape from have alot of german dubs which is quite annoying like game of thrones is dubbed

**Comment by gfxnick** [comment]
> @gfxnick ,
> 
> If things are dubbed, you can switch to `embed mode` while watching As for the scrapper, it's scrapes `vidsrc.pro` only, so we can't do anything as of now We are trying to scrapes other services

vidsrc.to direct links in there iframes and they are adfree example https://vid30c.site/e/51J0O435ZYQ8?t=4xjRAfUjBVMNxA%3D%3D&amp;ads=0&amp;src=vidsrc&amp;autostart=true but the link expire

**Comment by dev-AshishRanjan** [comment]
@gfxnick ,
we are using puppeteer and chromium and listening to for all the API requests there.
And in this environment `vidsrc.to` is not working.
Only vidsrc.pro is working
